### ISSUE TITLE
访问默认页面报错

### ISSUE THREAD

**Issue by mcc0624** [yingshang/ywljsec#1]
作者你好：
      我使用了您写的程序，程序正常启动后我访问默认页面127.0.0.1:8000和端口时候，有如下报错，劳烦您看下我的问题出在哪里，十分感谢！

`Internal Server Error: /
Traceback (most recent call last):
  File "F:\CTFD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "F:\CTFD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\软件\0x001\0x05\13\ywljsec\apps\views.py", line 20, in index
    parallel_users =  random.choices(parallelrs,k=2)
  File "c:\python39\lib\random.py", line 486, in choices
    return [population[floor(random() * n)] for i in _repeat(None, k)]
  File "c:\python39\lib\random.py", line 486, in <listcomp>
    return [population[floor(random() * n)] for i in _repeat(None, k)]
IndexError: list index out of range
[27/Jun/2022 01:08:49] "GET / HTTP/1.1" 500 74419
`
再次感谢！

**Comment by yingshang** [comment]
还没有写文档，需要先访问/init_data   接口进行初始化数据

**Comment by mcc0624** [comment]
嗯嗯，昨天晚上看views.py研究出来了，谢谢啦~
